fixed autocorr
neocortexdb/functime pull request #67
Opened 2023-10-08 16:58 UTC by abstractqqq

The issue is that in lazy Polars, slice behaves differently. The problem lies somewhere in its length calculation. Try running the following code, which will give us error in the lazy case. Since in our original code, we are just returning one expression at the end, the error didn't occur, but something inside was wrong.

```
df = pl.DataFrame({
    "a": [1,2,1,2,1,2],
    "b": [None, None, 1,1,1,1]
})

df.select(
    pl.col("a").slice(offset = 0, length=pl.count() - 2).alias("1"),
    pl.col("a").slice(offset = 1, length=pl.count() - 2).alias("2")
)

df.lazy().select(
    pl.col("a").slice(offset = 0, length=pl.count() - 2).alias("1"),
    pl.col("a").slice(offset = 1, length=pl.count() - 2).alias("2")
).collect()
```

I fixed the bug by reverting back to using shift, which will be slower than .head() / tail() / slice(), but will avoid using slice for now. We actually do not need to drop nulls after shifting, because dot product will null will just result in 0.

2023-10-08 23:53 UTC, topher-lo commented on functime/feature_extraction/tsfresh.py
> +def lempel_ziv_complexity(x: TIME_SERIES_T, value:Union[float, pl.Expr]) -> FLOAT_EXPR:
```suggestion
def lempel_ziv_complexity(x: TIME_SERIES_T, threshold:Union[float, pl.Expr]) -> FLOAT_EXPR:
```

2023-10-08 23:53 UTC, topher-lo requested changes
Just renamed `value` to `threshold`

2023-10-08 23:53 UTC, topher-lo commented on functime/feature_extraction/tsfresh.py
> +    value : float | pl.Expr
```suggestion
    threshold: float | pl.Expr
```

2023-10-08 23:53 UTC, topher-lo commented on functime/feature_extraction/tsfresh.py
> +        binary_seq = b"".join((x > value).cast(pl.Binary))
```suggestion
        binary_seq = b"".join((x > threshold).cast(pl.Binary))
```

2023-10-09 18:00 UTC, abstractqqq commented
@MathieuCayssol  Autocorrelation should be correct now. Please take a look

2023-10-09 18:07 UTC, MathieuCayssol commented
Sure, I will have a look. For the unit tests, the things you've updated, I already did it in the branch #66

2023-10-09 18:25 UTC, topher-lo approved these changes

2023-10-09 20:46 UTC, merged